name: Hello World

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo text
        run: |
          echo "Hello,world!"
          echo "comment #1"
          echo "comment #2"
